apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reminder-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/dwoolworth
    path: /nuxtjs-reminder-app
  project: default